parameters:
    dbstudios.cors_listener.allow_credentials: false

services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    DaybreakStudios\RestApiCommon\Responder:
        arguments:
            - '@app.serializer'

    DaybreakStudios\RestApiCommon\ResponderInterface: '@DaybreakStudios\RestApiCommon\Responder'

    DaybreakStudios\RestApiCommon\ResponderService: ~

    app.serializer:
        class: Symfony\Component\Serializer\Serializer
        arguments:
            -
                - '@app.serializer.normalizer.datetime'
                - '@app.serializer.normalizer.object'
            -
                - '@app.serializer.encoder.json'

    app.serializer.normalizer.datetime:
        class: Symfony\Component\Serializer\Normalizer\DateTimeNormalizer

    app.serializer.normalizer.object:
        class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer

    app.serializer.encoder.json:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder