<?php
	declare(strict_types=1);

	namespace DoctrineMigrations;

	use Doctrine\DBAL\Schema\Schema;
	use Doctrine\Migrations\AbstractMigration;

	/**
	 * Auto-generated Migration: Please modify to your needs!
	 */
	final class Version20200211163859 extends AbstractMigration {
		public function getDescription(): string {
			return '';
		}

		public function up(Schema $schema): void {
			// this up() migration is auto-generated, please modify it to your needs
			$this->abortIf(
				$this->connection->getDatabasePlatform()->getName() !== 'mysql',
				'Migration can only be executed safely on \'mysql\'.'
			);

			// This migration is a consolidation of the 72 migrations to date. No database changes are introduced with
			// this migration; it only serves to merge the previous changes into a single file.
			//
			// Running this file in a system whose database is up to date with the last minor release
			// (https://github.com/LartTyler/MHWDB-API/releases/tag/1.18.0) should have no effect on the database,
			// aside from clearing out the now non-extant migrations. New migrations created in the future should
			// continue to work as normal.
			if ($this->version->getConfiguration()->getNumberOfExecutedMigrations() > 0) {
				$this->warnIf(
					true,
					'Your schema contains previously executed migrations; assuming your schema is already up to date.' .
					'If this is not the case, drop your tables and try again, or try checking out ' .
					'https://github.com/LartTyler/MHWDB-API/releases/tag/1.18.0, running those migrations, and then ' .
					'attempt to run this migration again.'
				);

				$this->addSql('TRUNCATE ' . $this->version->getConfiguration()->getMigrationsTableName());
			} else {
				$this->addSql('CREATE TABLE crafting_material_costs (id INT UNSIGNED AUTO_INCREMENT NOT NULL, item_id INT UNSIGNED NOT NULL, quantity INT UNSIGNED NOT NULL, INDEX IDX_1B8FBFE6126F525E (item_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE weapon_assets (id INT UNSIGNED AUTO_INCREMENT NOT NULL, icon_id INT UNSIGNED DEFAULT NULL, image_id INT UNSIGNED DEFAULT NULL, INDEX IDX_442452A954B9D732 (icon_id), INDEX IDX_442452A93DA5256D (image_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE users (id INT UNSIGNED AUTO_INCREMENT NOT NULL, email VARCHAR(254) NOT NULL, display_name VARCHAR(32) NOT NULL, created_date DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', disabled TINYINT(1) NOT NULL, password VARCHAR(64) DEFAULT NULL, activation_code VARCHAR(64) DEFAULT NULL, password_reset_code VARCHAR(64) DEFAULT NULL, UNIQUE INDEX UNIQ_1483A5E9E7927C74 (email), UNIQUE INDEX UNIQ_1483A5E9D5499347 (display_name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE world_events (id INT UNSIGNED AUTO_INCREMENT NOT NULL, location_id INT UNSIGNED NOT NULL, type VARCHAR(128) NOT NULL, expansion VARCHAR(32) NOT NULL, platform VARCHAR(16) NOT NULL, start_timestamp DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', end_timestamp DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', quest_rank SMALLINT UNSIGNED NOT NULL, exclusive VARCHAR(16) DEFAULT NULL, master_rank TINYINT(1) NOT NULL, INDEX IDX_C3B92A0964D218E (location_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE armor (id INT UNSIGNED AUTO_INCREMENT NOT NULL, armor_set_id INT UNSIGNED DEFAULT NULL, assets_id INT UNSIGNED DEFAULT NULL, crafting_id INT UNSIGNED DEFAULT NULL, type VARCHAR(32) NOT NULL, rank VARCHAR(16) NOT NULL, rarity SMALLINT UNSIGNED NOT NULL, attributes LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', resist_fire INT NOT NULL, resist_water INT NOT NULL, resist_ice INT NOT NULL, resist_thunder INT NOT NULL, resist_dragon INT NOT NULL, defense_base INT UNSIGNED NOT NULL, defense_max INT UNSIGNED NOT NULL, defense_augmented INT UNSIGNED NOT NULL, INDEX IDX_BF27FEFC537E6F87 (armor_set_id), UNIQUE INDEX UNIQ_BF27FEFCE6AF163A (assets_id), UNIQUE INDEX UNIQ_BF27FEFC23BE98B5 (crafting_id), INDEX IDX_BF27FEFC8CDE5729 (type), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE armor_skill_ranks (armor_id INT UNSIGNED NOT NULL, skill_rank_id INT UNSIGNED NOT NULL, INDEX IDX_101D79CCF5AA3663 (armor_id), INDEX IDX_101D79CC6CE3F9A6 (skill_rank_id), PRIMARY KEY(armor_id, skill_rank_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE armor_set_bonus_ranks (id INT UNSIGNED AUTO_INCREMENT NOT NULL, bonus_id INT UNSIGNED NOT NULL, skill_id INT UNSIGNED NOT NULL, pieces SMALLINT UNSIGNED NOT NULL, INDEX IDX_5DF784FC69545666 (bonus_id), INDEX IDX_5DF784FC5585C142 (skill_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE monster_rewards (id INT UNSIGNED AUTO_INCREMENT NOT NULL, monster_id INT UNSIGNED NOT NULL, item_id INT UNSIGNED NOT NULL, INDEX IDX_4B43AF08C5FF1223 (monster_id), INDEX IDX_4B43AF08126F525E (item_id), UNIQUE INDEX UNIQ_4B43AF08C5FF1223126F525E (monster_id, item_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE monster_reward_conditions (monster_reward_id INT UNSIGNED NOT NULL, reward_condition_id INT UNSIGNED NOT NULL, INDEX IDX_B134FDFDDEA7E6 (monster_reward_id), INDEX IDX_B134FDFDE0BFB5A3 (reward_condition_id), PRIMARY KEY(monster_reward_id, reward_condition_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE weapon_crafting_info (id INT UNSIGNED AUTO_INCREMENT NOT NULL, previous_id INT UNSIGNED DEFAULT NULL, craftable TINYINT(1) NOT NULL, INDEX IDX_BBF70A542DE62210 (previous_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE weapon_crafting_info_branches (weapon_crafting_info_id INT UNSIGNED NOT NULL, weapon_id INT UNSIGNED NOT NULL, INDEX IDX_960A7F5CD4C2CCD2 (weapon_crafting_info_id), INDEX IDX_960A7F5C95B82273 (weapon_id), PRIMARY KEY(weapon_crafting_info_id, weapon_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE weapon_crafting_info_crafting_material_costs (weapon_crafting_info_id INT UNSIGNED NOT NULL, crafting_material_cost_id INT UNSIGNED NOT NULL, INDEX IDX_DCB3F113D4C2CCD2 (weapon_crafting_info_id), INDEX IDX_DCB3F113DD94392C (crafting_material_cost_id), PRIMARY KEY(weapon_crafting_info_id, crafting_material_cost_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE weapon_crafting_info_upgrade_material_costs (weapon_crafting_info_id INT UNSIGNED NOT NULL, crafting_material_cost_id INT UNSIGNED NOT NULL, INDEX IDX_B0AB8CFDD4C2CCD2 (weapon_crafting_info_id), INDEX IDX_B0AB8CFDDD94392C (crafting_material_cost_id), PRIMARY KEY(weapon_crafting_info_id, crafting_material_cost_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE skill_ranks (id INT UNSIGNED AUTO_INCREMENT NOT NULL, skill_id INT UNSIGNED NOT NULL, level SMALLINT UNSIGNED NOT NULL, modifiers LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', INDEX IDX_EECE33285585C142 (skill_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE weapon_phials (id INT UNSIGNED AUTO_INCREMENT NOT NULL, type VARCHAR(32) NOT NULL, damage SMALLINT UNSIGNED DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE armor_slots (id INT UNSIGNED AUTO_INCREMENT NOT NULL, armor_id INT UNSIGNED NOT NULL, rank SMALLINT UNSIGNED NOT NULL, INDEX IDX_24FFC0B8F5AA3663 (armor_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE ailment_recovery_methods (id INT UNSIGNED AUTO_INCREMENT NOT NULL, ailment_id INT UNSIGNED NOT NULL, actions LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', UNIQUE INDEX UNIQ_4C6AEAE5432CD43A (ailment_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE ailment_recovery_items (ailment_recovery_id INT UNSIGNED NOT NULL, item_id INT UNSIGNED NOT NULL, INDEX IDX_400DCBFE8B04118A (ailment_recovery_id), INDEX IDX_400DCBFE126F525E (item_id), PRIMARY KEY(ailment_recovery_id, item_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE charm_rank_crafting_info (id INT UNSIGNED AUTO_INCREMENT NOT NULL, craftable TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE charm_rank_crafting_info_crafting_material_costs (charm_rank_crafting_info_id INT UNSIGNED NOT NULL, crafting_material_cost_id INT UNSIGNED NOT NULL, INDEX IDX_8EEF4252357A2F3 (charm_rank_crafting_info_id), INDEX IDX_8EEF4252DD94392C (crafting_material_cost_id), PRIMARY KEY(charm_rank_crafting_info_id, crafting_material_cost_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE ailments (id INT UNSIGNED AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE user_roles (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT UNSIGNED NOT NULL, name VARCHAR(32) NOT NULL, INDEX IDX_54FCD59FA76ED395 (user_id), UNIQUE INDEX UNIQ_54FCD59FA76ED3955E237E06 (user_id, name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE armor_assets (id INT UNSIGNED AUTO_INCREMENT NOT NULL, image_male_id INT UNSIGNED DEFAULT NULL, image_female_id INT UNSIGNED DEFAULT NULL, INDEX IDX_3A541F11E88FF827 (image_male_id), INDEX IDX_3A541F11690AE98E (image_female_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE weapons (id INT UNSIGNED AUTO_INCREMENT NOT NULL, phial_id INT UNSIGNED DEFAULT NULL, crafting_id INT UNSIGNED DEFAULT NULL, assets_id INT UNSIGNED DEFAULT NULL, type VARCHAR(32) NOT NULL, rarity SMALLINT UNSIGNED NOT NULL, elderseal VARCHAR(16) DEFAULT NULL, coatings LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', special_ammo VARCHAR(32) DEFAULT NULL, deviation VARCHAR(32) DEFAULT NULL, boost_type VARCHAR(32) DEFAULT NULL, damage_type VARCHAR(32) DEFAULT NULL, attributes LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', attack_display SMALLINT UNSIGNED NOT NULL, attack_raw SMALLINT UNSIGNED NOT NULL, UNIQUE INDEX UNIQ_520EBBE11272188D (phial_id), UNIQUE INDEX UNIQ_520EBBE123BE98B5 (crafting_id), UNIQUE INDEX UNIQ_520EBBE1E6AF163A (assets_id), INDEX IDX_520EBBE18CDE5729 (type), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE weapon_durability (weapon_id INT UNSIGNED NOT NULL, weapon_sharpness_id INT UNSIGNED NOT NULL, INDEX IDX_F83322FA95B82273 (weapon_id), INDEX IDX_F83322FA974DCA88 (weapon_sharpness_id), PRIMARY KEY(weapon_id, weapon_sharpness_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE locations (id INT UNSIGNED AUTO_INCREMENT NOT NULL, zone_count SMALLINT UNSIGNED NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE weapon_ammo (id INT UNSIGNED AUTO_INCREMENT NOT NULL, weapon_id INT UNSIGNED NOT NULL, type VARCHAR(32) NOT NULL, capacities LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', INDEX IDX_579096D595B82273 (weapon_id), INDEX IDX_579096D58CDE5729 (type), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE monster_resistances (id INT UNSIGNED AUTO_INCREMENT NOT NULL, monster_id INT UNSIGNED NOT NULL, element VARCHAR(32) NOT NULL, _condition LONGTEXT DEFAULT NULL, INDEX IDX_7DE8A429C5FF1223 (monster_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE monsters (id INT UNSIGNED AUTO_INCREMENT NOT NULL, type VARCHAR(32) NOT NULL, species VARCHAR(32) NOT NULL, elements LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE monster_ailments (monster_id INT UNSIGNED NOT NULL, ailment_id INT UNSIGNED NOT NULL, INDEX IDX_3F33B44C5FF1223 (monster_id), INDEX IDX_3F33B44432CD43A (ailment_id), PRIMARY KEY(monster_id, ailment_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE monster_locations (monster_id INT UNSIGNED NOT NULL, location_id INT UNSIGNED NOT NULL, INDEX IDX_F35E41FDC5FF1223 (monster_id), INDEX IDX_F35E41FD64D218E (location_id), PRIMARY KEY(monster_id, location_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE charms (id INT UNSIGNED AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE decorations (id INT UNSIGNED AUTO_INCREMENT NOT NULL, slot SMALLINT UNSIGNED NOT NULL, rarity SMALLINT UNSIGNED NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE decorations_skill_ranks (decoration_id INT UNSIGNED NOT NULL, skill_rank_id INT UNSIGNED NOT NULL, INDEX IDX_5D2A04FA3446DFC4 (decoration_id), INDEX IDX_5D2A04FA6CE3F9A6 (skill_rank_id), PRIMARY KEY(decoration_id, skill_rank_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE motion_values (id INT UNSIGNED AUTO_INCREMENT NOT NULL, weapon_type VARCHAR(32) NOT NULL, damage_type VARCHAR(32) DEFAULT NULL, stun_potency SMALLINT UNSIGNED DEFAULT NULL, exhaust_potency SMALLINT UNSIGNED DEFAULT NULL, hits LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE ailment_strings (id INT UNSIGNED AUTO_INCREMENT NOT NULL, ailment_id INT UNSIGNED NOT NULL, name VARCHAR(32) NOT NULL, description LONGTEXT DEFAULT NULL, language VARCHAR(7) NOT NULL, UNIQUE INDEX UNIQ_CA3B2B475E237E06 (name), INDEX IDX_CA3B2B47432CD43A (ailment_id), UNIQUE INDEX UNIQ_CA3B2B47432CD43AD4DB71B5 (ailment_id, language), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE armor_set_bonus_strings (id INT UNSIGNED AUTO_INCREMENT NOT NULL, armor_set_bonus_id INT UNSIGNED NOT NULL, name VARCHAR(64) NOT NULL, language VARCHAR(7) NOT NULL, UNIQUE INDEX UNIQ_1E3E61D15E237E06 (name), INDEX IDX_1E3E61D1F0247870 (armor_set_bonus_id), UNIQUE INDEX UNIQ_1E3E61D1F0247870D4DB71B5 (armor_set_bonus_id, language), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE armor_strings (id INT UNSIGNED AUTO_INCREMENT NOT NULL, armor_id INT UNSIGNED NOT NULL, name VARCHAR(64) NOT NULL, language VARCHAR(7) NOT NULL, UNIQUE INDEX UNIQ_D46961425E237E06 (name), INDEX IDX_D4696142F5AA3663 (armor_id), UNIQUE INDEX UNIQ_D4696142F5AA3663D4DB71B5 (armor_id, language), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE location_strings (id INT UNSIGNED AUTO_INCREMENT NOT NULL, location_id INT UNSIGNED NOT NULL, name VARCHAR(32) NOT NULL, language VARCHAR(7) NOT NULL, UNIQUE INDEX UNIQ_5ADF79515E237E06 (name), INDEX IDX_5ADF795164D218E (location_id), UNIQUE INDEX UNIQ_5ADF795164D218ED4DB71B5 (location_id, language), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE monster_weakness_strings (id INT UNSIGNED AUTO_INCREMENT NOT NULL, monster_weakness_id INT UNSIGNED NOT NULL, _condition LONGTEXT DEFAULT NULL, language VARCHAR(7) NOT NULL, INDEX IDX_44F4CE7BB86BD44E (monster_weakness_id), UNIQUE INDEX UNIQ_44F4CE7BB86BD44ED4DB71B5 (monster_weakness_id, language), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE camp_strings (id INT UNSIGNED AUTO_INCREMENT NOT NULL, camp_id INT UNSIGNED NOT NULL, name VARCHAR(64) NOT NULL, language VARCHAR(7) NOT NULL, INDEX IDX_C409299B77075ABB (camp_id), UNIQUE INDEX UNIQ_C409299B77075ABBD4DB71B5 (camp_id, language), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE weapon_strings (id INT UNSIGNED AUTO_INCREMENT NOT NULL, weapon_id INT UNSIGNED NOT NULL, name VARCHAR(64) NOT NULL, language VARCHAR(7) NOT NULL, UNIQUE INDEX UNIQ_11AD2AB15E237E06 (name), INDEX IDX_11AD2AB195B82273 (weapon_id), UNIQUE INDEX UNIQ_11AD2AB195B82273D4DB71B5 (weapon_id, language), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE charm_rank_strings (id INT UNSIGNED AUTO_INCREMENT NOT NULL, charm_rank_id INT UNSIGNED NOT NULL, name VARCHAR(64) NOT NULL, language VARCHAR(7) NOT NULL, UNIQUE INDEX UNIQ_3E4E813A5E237E06 (name), INDEX IDX_3E4E813A3BA5C9D1 (charm_rank_id), UNIQUE INDEX UNIQ_3E4E813A3BA5C9D1D4DB71B5 (charm_rank_id, language), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE charm_strings (id INT UNSIGNED AUTO_INCREMENT NOT NULL, charm_id INT UNSIGNED NOT NULL, name VARCHAR(64) NOT NULL, language VARCHAR(7) NOT NULL, UNIQUE INDEX UNIQ_F929C4AB5E237E06 (name), INDEX IDX_F929C4AB93E9261F (charm_id), UNIQUE INDEX UNIQ_F929C4AB93E9261FD4DB71B5 (charm_id, language), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE skill_rank_strings (id INT UNSIGNED AUTO_INCREMENT NOT NULL, rank_id INT UNSIGNED NOT NULL, description LONGTEXT NOT NULL, language VARCHAR(7) NOT NULL, INDEX IDX_47A7FA57616678F (rank_id), UNIQUE INDEX UNIQ_47A7FA57616678FD4DB71B5 (rank_id, language), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE skill_strings (id INT UNSIGNED AUTO_INCREMENT NOT NULL, skill_id INT UNSIGNED NOT NULL, name VARCHAR(64) NOT NULL, description LONGTEXT NOT NULL, language VARCHAR(7) NOT NULL, UNIQUE INDEX UNIQ_AE6FF4DC5E237E06 (name), INDEX IDX_AE6FF4DC5585C142 (skill_id), UNIQUE INDEX UNIQ_AE6FF4DC5585C142D4DB71B5 (skill_id, language), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE decoration_strings (id INT UNSIGNED AUTO_INCREMENT NOT NULL, decoration_id INT UNSIGNED NOT NULL, name VARCHAR(64) NOT NULL, language VARCHAR(7) NOT NULL, UNIQUE INDEX UNIQ_CF00E3BD5E237E06 (name), INDEX IDX_CF00E3BD3446DFC4 (decoration_id), UNIQUE INDEX UNIQ_CF00E3BD3446DFC4D4DB71B5 (decoration_id, language), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE armor_set_strings (id INT UNSIGNED AUTO_INCREMENT NOT NULL, armor_set_id INT UNSIGNED NOT NULL, name VARCHAR(64) NOT NULL, language VARCHAR(7) NOT NULL, UNIQUE INDEX UNIQ_CDE5C6F65E237E06 (name), INDEX IDX_CDE5C6F6537E6F87 (armor_set_id), UNIQUE INDEX UNIQ_CDE5C6F6537E6F87D4DB71B5 (armor_set_id, language), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE monster_strings (id INT UNSIGNED AUTO_INCREMENT NOT NULL, monster_id INT UNSIGNED NOT NULL, name VARCHAR(64) NOT NULL, description LONGTEXT DEFAULT NULL, language VARCHAR(7) NOT NULL, UNIQUE INDEX UNIQ_16FBDBCA5E237E06 (name), INDEX IDX_16FBDBCAC5FF1223 (monster_id), UNIQUE INDEX UNIQ_16FBDBCAC5FF1223D4DB71B5 (monster_id, language), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE item_strings (id INT UNSIGNED AUTO_INCREMENT NOT NULL, item_id INT UNSIGNED NOT NULL, name VARCHAR(64) NOT NULL, description LONGTEXT NOT NULL, language VARCHAR(7) NOT NULL, UNIQUE INDEX UNIQ_BFC74CA15E237E06 (name), INDEX IDX_BFC74CA1126F525E (item_id), UNIQUE INDEX UNIQ_BFC74CA1126F525ED4DB71B5 (item_id, language), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE motion_value_strings (id INT UNSIGNED AUTO_INCREMENT NOT NULL, motion_value_id INT UNSIGNED NOT NULL, name VARCHAR(64) NOT NULL, language VARCHAR(7) NOT NULL, INDEX IDX_5735600541F7F30D (motion_value_id), UNIQUE INDEX UNIQ_5735600541F7F30DD4DB71B5 (motion_value_id, language), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE world_event_strings (id INT UNSIGNED AUTO_INCREMENT NOT NULL, event_id INT UNSIGNED NOT NULL, name VARCHAR(128) NOT NULL, description LONGTEXT DEFAULT NULL, requirements LONGTEXT DEFAULT NULL, success_conditions LONGTEXT DEFAULT NULL, language VARCHAR(7) NOT NULL, INDEX IDX_50C355E271F7E88B (event_id), UNIQUE INDEX UNIQ_50C355E271F7E88BD4DB71B5 (event_id, language), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE weapon_elements (id INT UNSIGNED AUTO_INCREMENT NOT NULL, weapon_id INT UNSIGNED NOT NULL, type VARCHAR(16) NOT NULL, damage SMALLINT UNSIGNED NOT NULL, hidden TINYINT(1) NOT NULL, INDEX IDX_355EB59495B82273 (weapon_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE skills (id INT UNSIGNED AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE camps (id INT UNSIGNED AUTO_INCREMENT NOT NULL, location_id INT UNSIGNED DEFAULT NULL, zone SMALLINT UNSIGNED NOT NULL, INDEX IDX_3D166BE564D218E (location_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE charm_ranks (id INT UNSIGNED AUTO_INCREMENT NOT NULL, charm_id INT UNSIGNED NOT NULL, crafting_id INT UNSIGNED DEFAULT NULL, level SMALLINT UNSIGNED NOT NULL, rarity SMALLINT UNSIGNED NOT NULL, INDEX IDX_DF91C65593E9261F (charm_id), UNIQUE INDEX UNIQ_DF91C65523BE98B5 (crafting_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE charm_ranks_skill_ranks (charm_rank_id INT UNSIGNED NOT NULL, skill_rank_id INT UNSIGNED NOT NULL, INDEX IDX_B86027C63BA5C9D1 (charm_rank_id), INDEX IDX_B86027C66CE3F9A6 (skill_rank_id), PRIMARY KEY(charm_rank_id, skill_rank_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE weapon_shelling (id INT UNSIGNED AUTO_INCREMENT NOT NULL, weapon_id INT UNSIGNED NOT NULL, type VARCHAR(16) NOT NULL, level SMALLINT UNSIGNED NOT NULL, UNIQUE INDEX UNIQ_9415F73295B82273 (weapon_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE armor_crafting_info (id INT UNSIGNED AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE armor_crafting_material_costs (armor_crafting_info_id INT UNSIGNED NOT NULL, crafting_material_cost_id INT UNSIGNED NOT NULL, INDEX IDX_8EE9EA587639D9A9 (armor_crafting_info_id), UNIQUE INDEX UNIQ_8EE9EA58DD94392C (crafting_material_cost_id), PRIMARY KEY(armor_crafting_info_id, crafting_material_cost_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE reward_conditions (id INT UNSIGNED AUTO_INCREMENT NOT NULL, type VARCHAR(32) NOT NULL, rank VARCHAR(16) NOT NULL, quantity SMALLINT UNSIGNED NOT NULL, chance SMALLINT UNSIGNED NOT NULL, subtype VARCHAR(128) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE armor_set_bonuses (id INT UNSIGNED AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE items (id INT UNSIGNED AUTO_INCREMENT NOT NULL, rarity SMALLINT UNSIGNED NOT NULL, _value INT UNSIGNED NOT NULL, carry_limit INT UNSIGNED NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE assets (id INT UNSIGNED AUTO_INCREMENT NOT NULL, uri LONGTEXT NOT NULL, primary_hash VARCHAR(128) NOT NULL, secondary_hash VARCHAR(128) NOT NULL, UNIQUE INDEX UNIQ_79D17D8E782B3D7070C66E9 (primary_hash, secondary_hash), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE weapon_slots (id INT UNSIGNED AUTO_INCREMENT NOT NULL, weapon_id INT UNSIGNED NOT NULL, rank SMALLINT UNSIGNED NOT NULL, INDEX IDX_E5CEC5B595B82273 (weapon_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE ailment_protection_methods (id INT UNSIGNED AUTO_INCREMENT NOT NULL, ailment_id INT UNSIGNED NOT NULL, UNIQUE INDEX UNIQ_5DBD6746432CD43A (ailment_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE ailment_protection_skills (ailment_protection_id INT UNSIGNED NOT NULL, skill_id INT UNSIGNED NOT NULL, INDEX IDX_517E18BFFE812F5B (ailment_protection_id), INDEX IDX_517E18BF5585C142 (skill_id), PRIMARY KEY(ailment_protection_id, skill_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE ailment_protection_items (ailment_protection_id INT UNSIGNED NOT NULL, item_id INT UNSIGNED NOT NULL, INDEX IDX_1051F85EFE812F5B (ailment_protection_id), INDEX IDX_1051F85E126F525E (item_id), PRIMARY KEY(ailment_protection_id, item_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE monster_weaknesses (id INT UNSIGNED AUTO_INCREMENT NOT NULL, monster_id INT UNSIGNED NOT NULL, element VARCHAR(32) NOT NULL, stars SMALLINT UNSIGNED NOT NULL, INDEX IDX_1D01676C5FF1223 (monster_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE armor_sets (id INT UNSIGNED AUTO_INCREMENT NOT NULL, bonus_id INT UNSIGNED DEFAULT NULL, rank VARCHAR(16) NOT NULL, INDEX IDX_7C8A0B1069545666 (bonus_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('CREATE TABLE weapon_sharpnesses (id INT UNSIGNED AUTO_INCREMENT NOT NULL, red INT UNSIGNED NOT NULL, orange INT UNSIGNED NOT NULL, yellow INT UNSIGNED NOT NULL, green INT UNSIGNED NOT NULL, blue INT UNSIGNED NOT NULL, white INT UNSIGNED NOT NULL, purple INT UNSIGNED NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
				$this->addSql('ALTER TABLE crafting_material_costs ADD CONSTRAINT FK_1B8FBFE6126F525E FOREIGN KEY (item_id) REFERENCES items (id)');
				$this->addSql('ALTER TABLE weapon_assets ADD CONSTRAINT FK_442452A954B9D732 FOREIGN KEY (icon_id) REFERENCES assets (id)');
				$this->addSql('ALTER TABLE weapon_assets ADD CONSTRAINT FK_442452A93DA5256D FOREIGN KEY (image_id) REFERENCES assets (id)');
				$this->addSql('ALTER TABLE world_events ADD CONSTRAINT FK_C3B92A0964D218E FOREIGN KEY (location_id) REFERENCES locations (id)');
				$this->addSql('ALTER TABLE armor ADD CONSTRAINT FK_BF27FEFC537E6F87 FOREIGN KEY (armor_set_id) REFERENCES armor_sets (id)');
				$this->addSql('ALTER TABLE armor ADD CONSTRAINT FK_BF27FEFCE6AF163A FOREIGN KEY (assets_id) REFERENCES armor_assets (id)');
				$this->addSql('ALTER TABLE armor ADD CONSTRAINT FK_BF27FEFC23BE98B5 FOREIGN KEY (crafting_id) REFERENCES armor_crafting_info (id)');
				$this->addSql('ALTER TABLE armor_skill_ranks ADD CONSTRAINT FK_101D79CCF5AA3663 FOREIGN KEY (armor_id) REFERENCES armor (id) ON DELETE CASCADE');
				$this->addSql('ALTER TABLE armor_skill_ranks ADD CONSTRAINT FK_101D79CC6CE3F9A6 FOREIGN KEY (skill_rank_id) REFERENCES skill_ranks (id) ON DELETE CASCADE');
				$this->addSql('ALTER TABLE armor_set_bonus_ranks ADD CONSTRAINT FK_5DF784FC69545666 FOREIGN KEY (bonus_id) REFERENCES armor_set_bonuses (id)');
				$this->addSql('ALTER TABLE armor_set_bonus_ranks ADD CONSTRAINT FK_5DF784FC5585C142 FOREIGN KEY (skill_id) REFERENCES skill_ranks (id)');
				$this->addSql('ALTER TABLE monster_rewards ADD CONSTRAINT FK_4B43AF08C5FF1223 FOREIGN KEY (monster_id) REFERENCES monsters (id)');
				$this->addSql('ALTER TABLE monster_rewards ADD CONSTRAINT FK_4B43AF08126F525E FOREIGN KEY (item_id) REFERENCES items (id)');
				$this->addSql('ALTER TABLE monster_reward_conditions ADD CONSTRAINT FK_B134FDFDDEA7E6 FOREIGN KEY (monster_reward_id) REFERENCES monster_rewards (id) ON DELETE CASCADE');
				$this->addSql('ALTER TABLE monster_reward_conditions ADD CONSTRAINT FK_B134FDFDE0BFB5A3 FOREIGN KEY (reward_condition_id) REFERENCES reward_conditions (id) ON DELETE CASCADE');
				$this->addSql('ALTER TABLE weapon_crafting_info ADD CONSTRAINT FK_BBF70A542DE62210 FOREIGN KEY (previous_id) REFERENCES weapons (id)');
				$this->addSql('ALTER TABLE weapon_crafting_info_branches ADD CONSTRAINT FK_960A7F5CD4C2CCD2 FOREIGN KEY (weapon_crafting_info_id) REFERENCES weapon_crafting_info (id) ON DELETE CASCADE');
				$this->addSql('ALTER TABLE weapon_crafting_info_branches ADD CONSTRAINT FK_960A7F5C95B82273 FOREIGN KEY (weapon_id) REFERENCES weapons (id) ON DELETE CASCADE');
				$this->addSql('ALTER TABLE weapon_crafting_info_crafting_material_costs ADD CONSTRAINT FK_DCB3F113D4C2CCD2 FOREIGN KEY (weapon_crafting_info_id) REFERENCES weapon_crafting_info (id) ON DELETE CASCADE');
				$this->addSql('ALTER TABLE weapon_crafting_info_crafting_material_costs ADD CONSTRAINT FK_DCB3F113DD94392C FOREIGN KEY (crafting_material_cost_id) REFERENCES crafting_material_costs (id) ON DELETE CASCADE');
				$this->addSql('ALTER TABLE weapon_crafting_info_upgrade_material_costs ADD CONSTRAINT FK_B0AB8CFDD4C2CCD2 FOREIGN KEY (weapon_crafting_info_id) REFERENCES weapon_crafting_info (id) ON DELETE CASCADE');
				$this->addSql('ALTER TABLE weapon_crafting_info_upgrade_material_costs ADD CONSTRAINT FK_B0AB8CFDDD94392C FOREIGN KEY (crafting_material_cost_id) REFERENCES crafting_material_costs (id) ON DELETE CASCADE');
				$this->addSql('ALTER TABLE skill_ranks ADD CONSTRAINT FK_EECE33285585C142 FOREIGN KEY (skill_id) REFERENCES skills (id)');
				$this->addSql('ALTER TABLE armor_slots ADD CONSTRAINT FK_24FFC0B8F5AA3663 FOREIGN KEY (armor_id) REFERENCES armor (id)');
				$this->addSql('ALTER TABLE ailment_recovery_methods ADD CONSTRAINT FK_4C6AEAE5432CD43A FOREIGN KEY (ailment_id) REFERENCES ailments (id)');
				$this->addSql('ALTER TABLE ailment_recovery_items ADD CONSTRAINT FK_400DCBFE8B04118A FOREIGN KEY (ailment_recovery_id) REFERENCES ailment_recovery_methods (id) ON DELETE CASCADE');
				$this->addSql('ALTER TABLE ailment_recovery_items ADD CONSTRAINT FK_400DCBFE126F525E FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE');
				$this->addSql('ALTER TABLE charm_rank_crafting_info_crafting_material_costs ADD CONSTRAINT FK_8EEF4252357A2F3 FOREIGN KEY (charm_rank_crafting_info_id) REFERENCES charm_rank_crafting_info (id) ON DELETE CASCADE');
				$this->addSql('ALTER TABLE charm_rank_crafting_info_crafting_material_costs ADD CONSTRAINT FK_8EEF4252DD94392C FOREIGN KEY (crafting_material_cost_id) REFERENCES crafting_material_costs (id) ON DELETE CASCADE');
				$this->addSql('ALTER TABLE user_roles ADD CONSTRAINT FK_54FCD59FA76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
				$this->addSql('ALTER TABLE armor_assets ADD CONSTRAINT FK_3A541F11E88FF827 FOREIGN KEY (image_male_id) REFERENCES assets (id)');
				$this->addSql('ALTER TABLE armor_assets ADD CONSTRAINT FK_3A541F11690AE98E FOREIGN KEY (image_female_id) REFERENCES assets (id)');
				$this->addSql('ALTER TABLE weapons ADD CONSTRAINT FK_520EBBE11272188D FOREIGN KEY (phial_id) REFERENCES weapon_phials (id)');
				$this->addSql('ALTER TABLE weapons ADD CONSTRAINT FK_520EBBE123BE98B5 FOREIGN KEY (crafting_id) REFERENCES weapon_crafting_info (id)');
				$this->addSql('ALTER TABLE weapons ADD CONSTRAINT FK_520EBBE1E6AF163A FOREIGN KEY (assets_id) REFERENCES weapon_assets (id)');
				$this->addSql('ALTER TABLE weapon_durability ADD CONSTRAINT FK_F83322FA95B82273 FOREIGN KEY (weapon_id) REFERENCES weapons (id) ON DELETE CASCADE');
				$this->addSql('ALTER TABLE weapon_durability ADD CONSTRAINT FK_F83322FA974DCA88 FOREIGN KEY (weapon_sharpness_id) REFERENCES weapon_sharpnesses (id) ON DELETE CASCADE');
				$this->addSql('ALTER TABLE weapon_ammo ADD CONSTRAINT FK_579096D595B82273 FOREIGN KEY (weapon_id) REFERENCES weapons (id)');
				$this->addSql('ALTER TABLE monster_resistances ADD CONSTRAINT FK_7DE8A429C5FF1223 FOREIGN KEY (monster_id) REFERENCES monsters (id)');
				$this->addSql('ALTER TABLE monster_ailments ADD CONSTRAINT FK_3F33B44C5FF1223 FOREIGN KEY (monster_id) REFERENCES monsters (id) ON DELETE CASCADE');
				$this->addSql('ALTER TABLE monster_ailments ADD CONSTRAINT FK_3F33B44432CD43A FOREIGN KEY (ailment_id) REFERENCES ailments (id) ON DELETE CASCADE');
				$this->addSql('ALTER TABLE monster_locations ADD CONSTRAINT FK_F35E41FDC5FF1223 FOREIGN KEY (monster_id) REFERENCES monsters (id) ON DELETE CASCADE');
				$this->addSql('ALTER TABLE monster_locations ADD CONSTRAINT FK_F35E41FD64D218E FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE CASCADE');
				$this->addSql('ALTER TABLE decorations_skill_ranks ADD CONSTRAINT FK_5D2A04FA3446DFC4 FOREIGN KEY (decoration_id) REFERENCES decorations (id) ON DELETE CASCADE');
				$this->addSql('ALTER TABLE decorations_skill_ranks ADD CONSTRAINT FK_5D2A04FA6CE3F9A6 FOREIGN KEY (skill_rank_id) REFERENCES skill_ranks (id) ON DELETE CASCADE');
				$this->addSql('ALTER TABLE ailment_strings ADD CONSTRAINT FK_CA3B2B47432CD43A FOREIGN KEY (ailment_id) REFERENCES ailments (id)');
				$this->addSql('ALTER TABLE armor_set_bonus_strings ADD CONSTRAINT FK_1E3E61D1F0247870 FOREIGN KEY (armor_set_bonus_id) REFERENCES armor_set_bonuses (id)');
				$this->addSql('ALTER TABLE armor_strings ADD CONSTRAINT FK_D4696142F5AA3663 FOREIGN KEY (armor_id) REFERENCES armor (id)');
				$this->addSql('ALTER TABLE location_strings ADD CONSTRAINT FK_5ADF795164D218E FOREIGN KEY (location_id) REFERENCES locations (id)');
				$this->addSql('ALTER TABLE monster_weakness_strings ADD CONSTRAINT FK_44F4CE7BB86BD44E FOREIGN KEY (monster_weakness_id) REFERENCES monster_weaknesses (id)');
				$this->addSql('ALTER TABLE camp_strings ADD CONSTRAINT FK_C409299B77075ABB FOREIGN KEY (camp_id) REFERENCES camps (id)');
				$this->addSql('ALTER TABLE weapon_strings ADD CONSTRAINT FK_11AD2AB195B82273 FOREIGN KEY (weapon_id) REFERENCES weapons (id)');
				$this->addSql('ALTER TABLE charm_rank_strings ADD CONSTRAINT FK_3E4E813A3BA5C9D1 FOREIGN KEY (charm_rank_id) REFERENCES charm_ranks (id)');
				$this->addSql('ALTER TABLE charm_strings ADD CONSTRAINT FK_F929C4AB93E9261F FOREIGN KEY (charm_id) REFERENCES charms (id)');
				$this->addSql('ALTER TABLE skill_rank_strings ADD CONSTRAINT FK_47A7FA57616678F FOREIGN KEY (rank_id) REFERENCES skill_ranks (id)');
				$this->addSql('ALTER TABLE skill_strings ADD CONSTRAINT FK_AE6FF4DC5585C142 FOREIGN KEY (skill_id) REFERENCES skills (id)');
				$this->addSql('ALTER TABLE decoration_strings ADD CONSTRAINT FK_CF00E3BD3446DFC4 FOREIGN KEY (decoration_id) REFERENCES decorations (id)');
				$this->addSql('ALTER TABLE armor_set_strings ADD CONSTRAINT FK_CDE5C6F6537E6F87 FOREIGN KEY (armor_set_id) REFERENCES armor_sets (id)');
				$this->addSql('ALTER TABLE monster_strings ADD CONSTRAINT FK_16FBDBCAC5FF1223 FOREIGN KEY (monster_id) REFERENCES monsters (id)');
				$this->addSql('ALTER TABLE item_strings ADD CONSTRAINT FK_BFC74CA1126F525E FOREIGN KEY (item_id) REFERENCES items (id)');
				$this->addSql('ALTER TABLE motion_value_strings ADD CONSTRAINT FK_5735600541F7F30D FOREIGN KEY (motion_value_id) REFERENCES motion_values (id)');
				$this->addSql('ALTER TABLE world_event_strings ADD CONSTRAINT FK_50C355E271F7E88B FOREIGN KEY (event_id) REFERENCES world_events (id)');
				$this->addSql('ALTER TABLE weapon_elements ADD CONSTRAINT FK_355EB59495B82273 FOREIGN KEY (weapon_id) REFERENCES weapons (id)');
				$this->addSql('ALTER TABLE camps ADD CONSTRAINT FK_3D166BE564D218E FOREIGN KEY (location_id) REFERENCES locations (id)');
				$this->addSql('ALTER TABLE charm_ranks ADD CONSTRAINT FK_DF91C65593E9261F FOREIGN KEY (charm_id) REFERENCES charms (id)');
				$this->addSql('ALTER TABLE charm_ranks ADD CONSTRAINT FK_DF91C65523BE98B5 FOREIGN KEY (crafting_id) REFERENCES charm_rank_crafting_info (id)');
				$this->addSql('ALTER TABLE charm_ranks_skill_ranks ADD CONSTRAINT FK_B86027C63BA5C9D1 FOREIGN KEY (charm_rank_id) REFERENCES charm_ranks (id) ON DELETE CASCADE');
				$this->addSql('ALTER TABLE charm_ranks_skill_ranks ADD CONSTRAINT FK_B86027C66CE3F9A6 FOREIGN KEY (skill_rank_id) REFERENCES skill_ranks (id) ON DELETE CASCADE');
				$this->addSql('ALTER TABLE weapon_shelling ADD CONSTRAINT FK_9415F73295B82273 FOREIGN KEY (weapon_id) REFERENCES weapons (id)');
				$this->addSql('ALTER TABLE armor_crafting_material_costs ADD CONSTRAINT FK_8EE9EA587639D9A9 FOREIGN KEY (armor_crafting_info_id) REFERENCES armor_crafting_info (id) ON DELETE CASCADE');
				$this->addSql('ALTER TABLE armor_crafting_material_costs ADD CONSTRAINT FK_8EE9EA58DD94392C FOREIGN KEY (crafting_material_cost_id) REFERENCES crafting_material_costs (id)');
				$this->addSql('ALTER TABLE weapon_slots ADD CONSTRAINT FK_E5CEC5B595B82273 FOREIGN KEY (weapon_id) REFERENCES weapons (id)');
				$this->addSql('ALTER TABLE ailment_protection_methods ADD CONSTRAINT FK_5DBD6746432CD43A FOREIGN KEY (ailment_id) REFERENCES ailments (id)');
				$this->addSql('ALTER TABLE ailment_protection_skills ADD CONSTRAINT FK_517E18BFFE812F5B FOREIGN KEY (ailment_protection_id) REFERENCES ailment_protection_methods (id) ON DELETE CASCADE');
				$this->addSql('ALTER TABLE ailment_protection_skills ADD CONSTRAINT FK_517E18BF5585C142 FOREIGN KEY (skill_id) REFERENCES skills (id) ON DELETE CASCADE');
				$this->addSql('ALTER TABLE ailment_protection_items ADD CONSTRAINT FK_1051F85EFE812F5B FOREIGN KEY (ailment_protection_id) REFERENCES ailment_protection_methods (id) ON DELETE CASCADE');
				$this->addSql('ALTER TABLE ailment_protection_items ADD CONSTRAINT FK_1051F85E126F525E FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE');
				$this->addSql('ALTER TABLE monster_weaknesses ADD CONSTRAINT FK_1D01676C5FF1223 FOREIGN KEY (monster_id) REFERENCES monsters (id)');
				$this->addSql('ALTER TABLE armor_sets ADD CONSTRAINT FK_7C8A0B1069545666 FOREIGN KEY (bonus_id) REFERENCES armor_set_bonuses (id)');
			}
		}

		public function down(Schema $schema): void {
			$this->throwIrreversibleMigrationException();
		}
	}
