App\Entity\Charm:
    type: entity
    table: charms
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 64
            nullable: false
            unique: true
        slug:
            type: string
            length: 64
            nullable: false
            unique: true
    oneToMany:
        ranks:
            targetEntity: App\Entity\CharmRank
            mappedBy: charm
            orphanRemoval: true
            cascade:
                - all