App\Entity\WeaponElement:
    type: entity
    table: weapon_elements
    uniqueConstraints:
        element_idx:
            columns:
                - weapon_id
                - type
    id:
        id:
            type: integer
            nullable: true
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: string
            length: 16
            nullable: false
        damage:
            type: smallint
            nullable: false
            options:
                unsigned: true
        hidden:
            type: boolean
            nullable: false
    manyToOne:
        weapon:
            targetEntity: App\Entity\Weapon
            inversedBy: elements
            joinColumn:
                nullable: false
                options:
                    unsigned: true