App\Entity\WeaponSharpness:
    type: entity
    table: weapon_sharpnesses
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        red:
            type: integer
            nullable: false
            options:
                unsigned: true
        orange:
            type: integer
            nullable: false
            options:
                unsigned: true
        yellow:
            type: integer
            nullable: false
            options:
                unsigned: true
        green:
            type: integer
            nullable: false
            options:
                unsigned: true
        blue:
            type: integer
            nullable: false
            options:
                unsigned: true